In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
import gc

df = pd.DataFrame()
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        path_dataset = os.path.join(dirname, filename)
        cols = list(pd.read_csv(path_dataset, nrows=1))
        df = pd.read_csv(path_dataset, usecols=[c for c in cols if c != 'Unnamed: 2'])
        print(path_dataset)

del cols
while gc.collect():
    pass
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/movies-dataset/movies.csv

In [2]:
df.head()

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1
0,"The Shining;""R"";""Drama"";1980;""June 13","1980 (United States)"";8.4;927000.0;""Stanley K..."
1,"The Blue Lagoon;""R"";""Adventure"";1980;""July 2","1980 (United States)"";5.8;65000.0;""Randal Kle..."
2,Star Wars: Episode V - The Empire Strikes Back...,"1980 (United States)"";8.7;1200000.0;""Irvin Ke..."
3,"Airplane!;""PG"";""Comedy"";1980;""July 2","1980 (United States)"";7.7;221000.0;""Jim Abrah..."
4,"Caddyshack;""R"";""Comedy"";1980;""July 25","1980 (United States)"";7.3;108000.0;""Harold Ra..."

In [3]:
df.tail()

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1
3995,"Birthday Girl;""R"";""Comedy"";2001;""February 1","2002 (United States)"";6.1;25000.0;""Jez Butter..."
3996,"Human Nature;""R"";""Comedy"";2001;""September 12","2001 (France)"";6.4;18000.0;""Michel Gondry"";""C..."
3997,"Made;""R"";""Comedy"";2001;""August 31","2001 (United States)"";6.4;18000.0;""Jon Favrea..."
3998,"One Night at McCool's;""R"";""Comedy"";2001;""April 27","2001 (United States)"";6.1;29000.0;""Harald Zwa..."
3999,"Dr. Dolittle 2;""PG"";""Comedy"";2001;""June 22","2001 (United States)"";4.7;42000.0;""Steve Carr..."

In [4]:
df.sample(5)

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1
751,"Invasion U.S.A.;""R"";""Action"";1985;""September 27","1985 (United States)"";5.5;9200.0;""Joseph Zito..."
1810,"A Tale of Springtime;""PG"";""Comedy"";1990;""April 4","1990 (France)"";7.2;4000.0;""Éric Rohmer"";""Éric..."
1700,"Night of the Living Dead;""R"";""Horror"";1990;""Oc...","1990 (United States)"";6.9;40000.0;""Tom Savini..."
629,"A Sunday in the Country;""G"";""Drama"";1984;""Apri...","1984 (France)"";7.6;2500.0;""Bertrand Tavernier..."
654,"St. Elmo's Fire;""R"";""Drama"";1985;""June 28","1985 (United States)"";6.4;38000.0;""Joel Schum..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                             --------------  -----
 0   name;"rating";"genre";"year";"released";"score";"votes";"director";"writer";"star";"country";"budget";"gross";"company";"runtime"  4000 non-null   object
 1   Unnamed: 1                                                                                                                         3947 non-null   object
dtypes: object(2)
memory usage: 62.6+ KB

In [6]:
def multiple_replaces(string, replacements):
    for old, new in replacements:
        string = string.replace(old, new)
    return string

In [7]:
cols = multiple_replaces(str(df.columns.values), [('"', ''), ('[', ''), (']', ''), (',', ''), ("'", ''), ('\n', ''), ('Unnamed: 1', ''), ('Unnamed: 2', '')])
cols = cols.strip().split(';')
cols

['name',
 'rating',
 'genre',
 'year',
 'released',
 'score',
 'votes',
 'director',
 'writer',
 'star',
 'country',
 'budget',
 'gross',
 'company',
 'runtime']

In [8]:
df = df.assign(
    DadosJuntos = lambda f: f.iloc[:, 0] + f.iloc[:, 1]
)

In [9]:
df[cols] = df['DadosJuntos'].str.split(';', expand=True)

In [10]:
df

,"name;""rating"";""genre"";""year"";""released"";""score"";""votes"";""director"";""writer"";""star"";""country"";""budget"";""gross"";""company"";""runtime""",Unnamed: 1,DadosJuntos,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,"The Shining;""R"";""Drama"";1980;""June 13","1980 (United States)"";8.4;927000.0;""Stanley K...","The Shining;""R"";""Drama"";1980;""June 13 1980 (Un...",The Shining,"""R""","""Drama""",1980,"""June 13 1980 (United States)""",8.4,927000.0,"""Stanley Kubrick""","""Stephen King""","""Jack Nicholson""","""United Kingdom""",19000000,"""46998772.0""","""Warner Bros.""",146.0
1,"The Blue Lagoon;""R"";""Adventure"";1980;""July 2","1980 (United States)"";5.8;65000.0;""Randal Kle...","The Blue Lagoon;""R"";""Adventure"";1980;""July 2 1...",The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2 1980 (United States)""",5.8,65000.0,"""Randal Kleiser""","""Henry De Vere Stacpoole""","""Brooke Shields""","""United States""",4500000,"""58853106.0""","""Columbia Pictures""",104.0
2,Star Wars: Episode V - The Empire Strikes Back...,"1980 (United States)"";8.7;1200000.0;""Irvin Ke...",Star Wars: Episode V - The Empire Strikes Back...,Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20 1980 (United States)""",8.7,1200000.0,"""Irvin Kershner""","""Leigh Brackett""","""Mark Hamill""","""United States""",18000000,"""538375067.0""","""Lucasfilm""",124.0
3,"Airplane!;""PG"";""Comedy"";1980;""July 2","1980 (United States)"";7.7;221000.0;""Jim Abrah...","Airplane!;""PG"";""Comedy"";1980;""July 2 1980 (Uni...",Airplane!,"""PG""","""Comedy""",1980,"""July 2 1980 (United States)""",7.7,221000.0,"""Jim Abrahams""","""Jim Abrahams""","""Robert Hays""","""United States""",3500000,"""83453539.0""","""Paramount Pictures""",88.0
4,"Caddyshack;""R"";""Comedy"";1980;""July 25","1980 (United States)"";7.3;108000.0;""Harold Ra...","Caddyshack;""R"";""Comedy"";1980;""July 25 1980 (Un...",Caddyshack,"""R""","""Comedy""",1980,"""July 25 1980 (United States)""",7.3,108000.0,"""Harold Ramis""","""Brian Doyle-Murray""","""Chevy Chase""","""United States""",6000000,"""39846344.0""","""Orion Pictures""",98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,"Birthday Girl;""R"";""Comedy"";2001;""February 1","2002 (United States)"";6.1;25000.0;""Jez Butter...","Birthday Girl;""R"";""Comedy"";2001;""February 1 20...",Birthday Girl,"""R""","""Comedy""",2001,"""February 1 2002 (United States)""",6.1,25000.0,"""Jez Butterworth""","""Tom Butterworth""","""Nicole Kidman""","""United Kingdom""",13000000,"""16171098.0""","""FilmFour""",93.0
3996,"Human Nature;""R"";""Comedy"";2001;""September 12","2001 (France)"";6.4;18000.0;""Michel Gondry"";""C...","Human Nature;""R"";""Comedy"";2001;""September 12 2...",Human Nature,"""R""","""Comedy""",2001,"""September 12 2001 (France)""",6.4,18000.0,"""Michel Gondry""","""Charlie Kaufman""","""Tim Robbins""","""France""",0,"""1574660.0""","""Fine Line Features""",96.0
3997,"Made;""R"";""Comedy"";2001;""August 31","2001 (United States)"";6.4;18000.0;""Jon Favrea...","Made;""R"";""Comedy"";2001;""August 31 2001 (United...",Made,"""R""","""Comedy""",2001,"""August 31 2001 (United States)""",6.4,18000.0,"""Jon Favreau""","""Jon Favreau""","""Vince Vaughn""","""United States""",5000000,"""5480653.0""","""Artisan Entertainment""",95.0
3998,"One Night at McCool's;""R"";""Comedy"";2001;""April 27","2001 (United States)"";6.1;29000.0;""Harald Zwa...","One Night at McCool's;""R"";""Comedy"";2001;""April...",One Night at McCool's,"""R""","""Comedy""",2001,"""April 27 2001 (United States)""",6.1,29000.0,"""Harald Zwart""","""Stan Seidel""","""Liv Tyler""","""United States""",18000000,"""13578186.0""","""October Films""",93.0
3999,"Dr. Dolittle 2;""PG"";""Comedy"";2001;""June 22","2001 (United States)"";4.7;42000.0;""Steve Carr...","Dr. Dolittle 2;""PG"";""Comedy"";2001;""June 22 200...",Dr. Dolittle 2,"""PG""","""Comedy""",2001,"""June 22 2001 (United States)""",4.7,42000.0,"""Steve Carr""","""Hugh Lofting""","""Eddie Murphy""","""United States""",70000000,"""176104344.0""","""Twentieth Century Fox""",87.0

In [11]:
df.drop(columns=df.columns[:3], axis=1, inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      3947 non-null   object
 1   rating    3947 non-null   object
 2   genre     3947 non-null   object
 3   year      3947 non-null   object
 4   released  3947 non-null   object
 5   score     3947 non-null   object
 6   votes     3947 non-null   object
 7   director  3947 non-null   object
 8   writer    3947 non-null   object
 9   star      3947 non-null   object
 10  country   3947 non-null   object
 11  budget    3947 non-null   object
 12  gross     3947 non-null   object
 13  company   3947 non-null   object
 14  runtime   3940 non-null   object
dtypes: object(15)
memory usage: 468.9+ KB

In [13]:
df.loc[lambda f: f.duplicated() == True].isnull().sum()

name        52
rating      52
genre       52
year        52
released    52
score       52
votes       52
director    52
writer      52
star        52
country     52
budget      52
gross       52
company     52
runtime     52
dtype: int64

In [14]:
df.dropna(how='all', inplace=True)

In [15]:
df.isnull().sum()

name        0
rating      0
genre       0
year        0
released    0
score       0
votes       0
director    0
writer      0
star        0
country     0
budget      0
gross       0
company     0
runtime     7
dtype: int64

In [16]:
df['runtime'].fillna(0, inplace=True)

In [17]:
df.isnull().sum()

name        0
rating      0
genre       0
year        0
released    0
score       0
votes       0
director    0
writer      0
star        0
country     0
budget      0
gross       0
company     0
runtime     0
dtype: int64

In [18]:
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,"""R""","""Drama""",1980,"""June 13 1980 (United States)""",8.4,927000.0,"""Stanley Kubrick""","""Stephen King""","""Jack Nicholson""","""United Kingdom""",19000000,"""46998772.0""","""Warner Bros.""",146.0
1,The Blue Lagoon,"""R""","""Adventure""",1980,"""July 2 1980 (United States)""",5.8,65000.0,"""Randal Kleiser""","""Henry De Vere Stacpoole""","""Brooke Shields""","""United States""",4500000,"""58853106.0""","""Columbia Pictures""",104.0
2,Star Wars: Episode V - The Empire Strikes Back,"""PG""","""Action""",1980,"""June 20 1980 (United States)""",8.7,1200000.0,"""Irvin Kershner""","""Leigh Brackett""","""Mark Hamill""","""United States""",18000000,"""538375067.0""","""Lucasfilm""",124.0
3,Airplane!,"""PG""","""Comedy""",1980,"""July 2 1980 (United States)""",7.7,221000.0,"""Jim Abrahams""","""Jim Abrahams""","""Robert Hays""","""United States""",3500000,"""83453539.0""","""Paramount Pictures""",88.0
4,Caddyshack,"""R""","""Comedy""",1980,"""July 25 1980 (United States)""",7.3,108000.0,"""Harold Ramis""","""Brian Doyle-Murray""","""Chevy Chase""","""United States""",6000000,"""39846344.0""","""Orion Pictures""",98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,"""R""","""Comedy""",2001,"""February 1 2002 (United States)""",6.1,25000.0,"""Jez Butterworth""","""Tom Butterworth""","""Nicole Kidman""","""United Kingdom""",13000000,"""16171098.0""","""FilmFour""",93.0
3996,Human Nature,"""R""","""Comedy""",2001,"""September 12 2001 (France)""",6.4,18000.0,"""Michel Gondry""","""Charlie Kaufman""","""Tim Robbins""","""France""",0,"""1574660.0""","""Fine Line Features""",96.0
3997,Made,"""R""","""Comedy""",2001,"""August 31 2001 (United States)""",6.4,18000.0,"""Jon Favreau""","""Jon Favreau""","""Vince Vaughn""","""United States""",5000000,"""5480653.0""","""Artisan Entertainment""",95.0
3998,One Night at McCool's,"""R""","""Comedy""",2001,"""April 27 2001 (United States)""",6.1,29000.0,"""Harald Zwart""","""Stan Seidel""","""Liv Tyler""","""United States""",18000000,"""13578186.0""","""October Films""",93.0
3999,Dr. Dolittle 2,"""PG""","""Comedy""",2001,"""June 22 2001 (United States)""",4.7,42000.0,"""Steve Carr""","""Hugh Lofting""","""Eddie Murphy""","""United States""",70000000,"""176104344.0""","""Twentieth Century Fox""",87.0

In [19]:
df = df.assign(
    date = lambda f: pd.to_datetime((f['released'].str.split(' ', expand=True)[1] + '/' + f['released'].str.split(' ', expand=True)[0] + '/' + f['year']).str.replace('"', ''), format='%d/%B/%Y'),
    month = lambda f: f['date'].dt.month,
    year = lambda f: f['date'].dt.year,
    day = lambda f: f['date'].dt.day,
    country = lambda f: (f['released'].str.split(' ', expand=True)[3] + ' ' + f['released'].str.split(' ', expand=True)[4]).str.replace('["()]', '', regex=True)
).drop(['released', 'date'], axis=1).replace('"', '', regex=True)

In [20]:
df['country'].fillna('País não informado', inplace=True)

In [21]:
df.isnull().sum()

name        0
rating      0
genre       0
year        0
score       0
votes       0
director    0
writer      0
star        0
country     0
budget      0
gross       0
company     0
runtime     0
month       0
day         0
dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3947 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      3947 non-null   object
 1   rating    3947 non-null   object
 2   genre     3947 non-null   object
 3   year      3947 non-null   int64
 4   score     3947 non-null   object
 5   votes     3947 non-null   object
 6   director  3947 non-null   object
 7   writer    3947 non-null   object
 8   star      3947 non-null   object
 9   country   3947 non-null   object
 10  budget    3947 non-null   object
 11  gross     3947 non-null   object
 12  company   3947 non-null   object
 13  runtime   3947 non-null   object
 14  month     3947 non-null   int64
 15  day       3947 non-null   int64
dtypes: int64(3), object(13)
memory usage: 524.2+ KB

In [23]:
df

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,month,day
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000,46998772.0,Warner Bros.,146.0,6,13
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,7,2
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,6,20
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,7,2
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,7,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United States,13000000,16171098.0,FilmFour,93.0,2,1
3996,Human Nature,R,Comedy,2001,6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,País não informado,0,1574660.0,Fine Line Features,96.0,9,12
3997,Made,R,Comedy,2001,6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,8,31
3998,One Night at McCool's,R,Comedy,2001,6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,4,27
3999,Dr. Dolittle 2,PG,Comedy,2001,4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,6,22

In [24]:
def count_values(col):
    return df[col].value_counts()

In [25]:
# df.assign(
#     rating = lambda f: f['rating'].replace('X', 'NC-17', regex=True),
#     rating = lambda f: f['rating'].replace('Not Rated', 'NR', regex=True),
#     rating = lambda f: f['rating'].replace('Unrated', 'UR', regex=True),
#     rating = lambda f: f['rating'].replace('Approved', 'This Film Is Not Yet Rated', regex=True),
#     rating = lambda f: f['rating'].replace('TV-PG', 'PG', regex=True),
#     rating = lambda f: f['rating'].replace('TV-MA', 'R', regex=True)
# )['rating'].value_counts()
# x replace to NC-17
df['rating'] = df['rating'].replace('X', 'NC-17', regex=True)
df['rating'] = df['rating'].replace('Not Rated', 'NR', regex=True)
df['rating'] = df['rating'].replace('Unrated', 'UR', regex=True)
df['rating'] = df['rating'].replace('Approved', 'This Film Is Not Yet Rated', regex=True)
df['rating'] = df['rating'].replace('TV-PG', 'PG', regex=True)
df['rating'] = df['rating'].replace('TV-MA', 'R', regex=True)
df['rating'] = df['rating'].replace('', 'This Film Is Not Yet Rated', regex=True)

count_values('rating')

R                             2017
PG-13                          841
PG                             810
G                              105
NR                              87
This Film Is Not Yet Rated      40
UR                              30
NC-17                           17
Name: rating, dtype: int64

In [26]:
count_values('genre')

Comedy       1338
Drama         787
Action        773
Crime         296
Adventure     230
Biography     173
Horror        157
Animation     113
Fantasy        32
Mystery        12
Thriller        9
Romance         8
Family          8
Sci-Fi          6
Western         3
Music           1
History         1
Name: genre, dtype: int64

In [27]:
count_values('country')

United States         3628
País não informado     235
United Kingdom          60
Hong Kong                8
South Korea              6
West Germany             6
Soviet Union             1
South Africa             1
New Zealand              1
Federal Republic         1
Name: country, dtype: int64

In [28]:
df = df.assign(
    rating = lambda f: f['rating'].astype('category'),
    genre = lambda f: f['genre'].astype('category'),
    country = lambda f: f['country'].astype('category')
)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3947 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      3947 non-null   object
 1   rating    3947 non-null   category
 2   genre     3947 non-null   category
 3   year      3947 non-null   int64
 4   score     3947 non-null   object
 5   votes     3947 non-null   object
 6   director  3947 non-null   object
 7   writer    3947 non-null   object
 8   star      3947 non-null   object
 9   country   3947 non-null   category
 10  budget    3947 non-null   object
 11  gross     3947 non-null   object
 12  company   3947 non-null   object
 13  runtime   3947 non-null   object
 14  month     3947 non-null   int64
 15  day       3947 non-null   int64
dtypes: category(3), int64(3), object(10)
memory usage: 444.7+ KB

In [30]:
df

,name,rating,genre,year,score,votes,director,writer,star,country,budget,gross,company,runtime,month,day
0,The Shining,R,Drama,1980,8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000,46998772.0,Warner Bros.,146.0,6,13
1,The Blue Lagoon,R,Adventure,1980,5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,7,2
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,6,20
3,Airplane!,PG,Comedy,1980,7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,7,2
4,Caddyshack,R,Comedy,1980,7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,7,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United States,13000000,16171098.0,FilmFour,93.0,2,1
3996,Human Nature,R,Comedy,2001,6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,País não informado,0,1574660.0,Fine Line Features,96.0,9,12
3997,Made,R,Comedy,2001,6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,8,31
3998,One Night at McCool's,R,Comedy,2001,6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,4,27
3999,Dr. Dolittle 2,PG,Comedy,2001,4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,6,22

In [31]:
df = df.assign(
    score = lambda f: f['score'].astype(float),
    votes = lambda f: f['votes'].astype(float).astype(np.uint),
    budget = lambda f: f['budget'].astype(np.uint),
    gross = lambda f: f['gross'].replace('', 0, regex=True).astype(float),
    runtime = lambda f: f['runtime'].astype(float).astype(np.uint8),
    month = lambda f: f['month'].astype(np.uint8),
    day = lambda f: f['day'].astype(np.uint8),
    year = lambda f: f['year'].astype(np.uint16)
)

In [32]:
df.describe()

,year,score,votes,budget,gross,runtime,month,day
count,3947.000000,3947.000000,3.947000e+03,3.947000e+03,3.947000e+03,3947.000000,3947.000000,3947.000000
mean,1991.234609,6.318596,5.515430e+04,1.561524e+07,4.048302e+07,105.419052,6.585761,16.004307
std,5.949329,0.977161,1.436098e+05,2.257366e+07,9.150123e+07,18.500208,3.436769,8.559338
min,1980.000000,2.200000,5.100000e+01,0.000000e+00,0.000000e+00,0.000000,1.000000,1.000000
25%,1986.000000,5.700000,4.400000e+03,0.000000e+00,2.358688e+06,94.000000,4.000000,9.000000
50%,1991.000000,6.400000,1.400000e+04,7.500000e+06,1.113221e+07,102.000000,7.000000,16.000000
75%,1996.000000,7.000000,4.600000e+04,2.200000e+07,3.435846e+07,114.000000,10.000000,23.000000
max,2001.000000,9.300000,2.400000e+06,2.000000e+08,2.201647e+09,242.000000,12.000000,31.000000

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3947 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      3947 non-null   object
 1   rating    3947 non-null   category
 2   genre     3947 non-null   category
 3   year      3947 non-null   uint16
 4   score     3947 non-null   float64
 5   votes     3947 non-null   uint64
 6   director  3947 non-null   object
 7   writer    3947 non-null   object
 8   star      3947 non-null   object
 9   country   3947 non-null   category
 10  budget    3947 non-null   uint64
 11  gross     3947 non-null   float64
 12  company   3947 non-null   object
 13  runtime   3947 non-null   uint8
 14  month     3947 non-null   uint8
 15  day       3947 non-null   uint8
dtypes: category(3), float64(2), object(5), uint16(1), uint64(2), uint8(3)
memory usage: 340.6+ KB

In [34]:
renomeia_colunas = {
    'name': 'nome',
    'rating': 'classificacao',
    'genre': 'genero',
    'year': 'ano',
    'score': 'pontuacao',
    'votes': 'votos',
    'director': 'diretor',
    'writer': 'escritor',
    'star': 'estrela do filme',
    'country': 'pais',
    'budget': 'orcamento ($)',
    'gross': 'lucro bruto ($)',
    'company': 'companhia',
    'runtime': 'duracao do filme (min)',
    'month': 'mes',
    'day': 'dia'
}

In [35]:
df.rename(columns=renomeia_colunas, inplace=True)

In [36]:
df

,nome,classificacao,genero,ano,pontuacao,votos,diretor,escritor,estrela do filme,pais,orcamento ($),lucro bruto ($),companhia,duracao do filme (min),mes,dia
0,The Shining,R,Drama,1980,8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United States,19000000,46998772.0,Warner Bros.,146,6,13
1,The Blue Lagoon,R,Adventure,1980,5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104,7,2
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124,6,20
3,Airplane!,PG,Comedy,1980,7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88,7,2
4,Caddyshack,R,Comedy,1980,7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98,7,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,6.1,25000,Jez Butterworth,Tom Butterworth,Nicole Kidman,United States,13000000,16171098.0,FilmFour,93,2,1
3996,Human Nature,R,Comedy,2001,6.4,18000,Michel Gondry,Charlie Kaufman,Tim Robbins,País não informado,0,1574660.0,Fine Line Features,96,9,12
3997,Made,R,Comedy,2001,6.4,18000,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95,8,31
3998,One Night at McCool's,R,Comedy,2001,6.1,29000,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93,4,27
3999,Dr. Dolittle 2,PG,Comedy,2001,4.7,42000,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87,6,22